"""Fail-closed complete230 arithmetic replay, using only the standard library."""
import argparse,hashlib,json,shutil,subprocess,sys,tempfile
from pathlib import Path
HERE=Path(__file__).resolve().parent;ROOT=HERE.parent
PINS={'packet/stage08/STAGE08_RESULT.json':'224486fbd98b5dc11e8a0eccbca8d69cb151c2021c1157084cf9771ad37ce287',
      'packet/stage09/STAGE09_RESULT.json':'01265dd05fadcf550a4fb3190f60e8420f78caea186bfe7bc82b2a9c16b38e63',
      'independent_230.py':'b4b88e53701398e46b8fd1277ffa3e6c92675f958b785ad8fee65a06f188a64d'}
def need(ok,msg):
    if not ok:raise ValueError(msg)
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def read(p):return json.loads(p.read_text(encoding='utf-8'))
def flags():return ['-B']+(['-O'] if sys.flags.optimize else [])
def check_source():
    for name,pin in PINS.items():need(sha(HERE/name)==pin,'frozen mathematical source '+name)
    rev=read(HERE/'REVIEW_STATUS.json');need(rev['status']=='PASS_WITH_LIMITS' and rev['mathematical_gaps_found']==rev['required_mathematical_edits']==[] and rev['qualified_human_acceptance'] is False and rev['formal_kernel_acceptance'] is False and rev['priority_certification'] is False,'review scope')
    provenance=read(HERE/'SOURCE_PROVENANCE.json')
    for e in provenance['exact_sources_and_transformations']:
        p=ROOT/e['destination']
        if e['transformation']=='exact byte copy':need(sha(p)==e['source_sha256'],'exact reviewed byte copy '+e['destination'])
        else:
            text=p.read_bytes().decode('utf-8');body=text[text.index('## 1. Definitions'):text.index('## 11. Dependencies')]
            need(hashlib.sha256(body.encode('utf-8')).hexdigest()==e['mathematical_sections_1_through10_sha256'],'reviewed mathematical proof body')
def inventory():
    doc=read(ROOT/'PUBLIC_MANIFEST.json');need(doc['schema']=='c54-16-4-combined-public-audit-230-v01','public230 inventory schema')
    paths=[]
    for e in doc['files']:
        if e['path'].startswith('audit230/'):
            p=ROOT/e['path'];need(p.is_file() and p.stat().st_size==e['bytes'] and sha(p)==e['sha256'],'public230 inventory member');paths.append(e['path'])
    actual=sorted(p.relative_to(ROOT).as_posix() for p in HERE.rglob('*') if p.is_file());need(sorted(paths)==actual and len(paths)==len(set(paths)),'complete audit230 inventory')
    return len(paths)
def replay(workdir=None):
    check_source();mode='OPTIMIZED' if sys.flags.optimize else 'NORMAL';records=[]
    with tempfile.TemporaryDirectory(prefix='c54-public230-check-',dir=workdir) as name:
        temp=Path(name);need(temp.resolve().is_relative_to((Path(workdir) if workdir else Path(tempfile.gettempdir())).resolve()),'scratch directory outside selected root')
        shutil.copytree(HERE/'packet',temp/'packet');shutil.copyfile(HERE/'independent_230.py',temp/'independent_230.py')
        shutil.copyfile(HERE/'semantic_boundaries.py',temp/'semantic_boundaries.py')
        for number in ['08','09']:
            d=temp/'packet'/('stage'+number);out='FRESH_'+mode+'.json'
            proc=subprocess.run([sys.executable,*flags(),'verify_stage'+number+'.py','STAGE'+number+'_RESULT.json',out],cwd=d,capture_output=True,text=True,timeout=21)
            need(proc.returncode==0 and (d/out).is_file(),'complete stage'+number+' reconstruction failed')
            raw=(d/out).read_bytes();expected=(HERE/'packet'/('stage'+number)/('STAGE'+number+'_'+mode+'.json'))
            if number=='09':
                # This frozen receipt is generated by the exact audited checker;
                # comparison is to the mathematical closure below, not a missing file.
                r=json.loads(raw);need(r['case_count']==15 and r['reconstructed_row_maxima']==48 and r['all18_pair_covers_excluded'] is True and r['minimum_rank_slack']==[686878,1225],'complete refined exclusion')
            else:need(json.loads(raw)==read(expected),'frozen complete stage08 mathematics differs')
            records.append(json.loads(raw))
        proc=subprocess.run([sys.executable,*flags(),'independent_230.py'],cwd=temp,capture_output=True,text=True,timeout=21)
        need(proc.returncode==0,'third complete independent reconstruction failed')
        independent=read(temp/('INDEPENDENT_'+mode+'.json'))
        need(len(independent['macro_cases'])==70 and len(independent['full_joint_cases'])==574 and len(independent['refined_cases'])==15 and
             independent['full_row_maxima']==2363 and independent['refined_row_maxima']==48 and independent['all_refined_excluded'] is True and
             independent['minimum_refined_gap']==[686878,1225] and independent['pair_floor']==19 and independent['child_floor']==68 and independent['parent_floor']==230 and
             independent['previous227_assumed'] is False,'complete independent closure and lifts')
        math={k:v for k,v in independent.items() if k!='elapsed_seconds'}
        digest=hashlib.sha256(json.dumps(math,sort_keys=True,separators=(',',':')).encode()).hexdigest()
        proc=subprocess.run([sys.executable,*flags(),'semantic_boundaries.py'],cwd=temp,capture_output=True,text=True,timeout=21)
        need(proc.returncode==0,'complete repeated-row/binary boundary checks failed');boundaries=read(temp/'SEMANTIC_BOUNDARY_RECEIPT.json')
        need(boundaries['toy_pair_cover_families']==177100 and boundaries['complete_toy_pair_covers']==30 and boundaries['plain_twin_cases_kept']==56 and boundaries['target_ones_independence_uses_strict_16_below_18'] is True,'complete declared semantic boundary universes')
    check_source()
    return {'status':'PASS_COMPLETE_PUBLIC230_ARITHMETIC_WITH_SEMANTIC_REVIEW_LIMITS','theorems':['C(52,14,2)>=19','C(53,15,3)>=68','C(54,16,4)>=230'],
        'stage08':records[0],'stage09':records[1],'third_independent_math_sha256':digest,
        'semantic_boundaries':boundaries,
        'complete_macro_cases':70,'complete_joint_types':574,'complete_refined_types':15,'complete_row_maxima':2411,
        'minimum_refined_rank_gap':[686878,1225],'internal_semantic_review':'PASS_WITH_LIMITS','upper_bound_recorded':336,'upper_credit':'Franco Atzeni',
        'qualified_human_accepted':False,'formal_kernel_verified':False,'priority_certified':False,'exact_covering_number_claimed':False,
        'producer_runs':0,'cover_searches':0,'network_calls':0,'source_integrity_rechecked':True}
def main():
    parser=argparse.ArgumentParser(description=__doc__);parser.add_argument('--check-manifest',action='store_true');parser.add_argument('--work-dir',type=Path,help='Existing writable parent for temporary checks');args=parser.parse_args()
    if args.work_dir:need(args.work_dir.is_dir(),'existing writable scratch parent required')
    if args.check_manifest:inventory()
    result=replay(args.work_dir)
    if args.check_manifest:result['audit230_manifest_files']=inventory()
    print(json.dumps(result,indent=2,sort_keys=True))
if __name__=='__main__':
    try:main()
    except Exception as exc:print('FAIL_CLOSED: '+str(exc),file=sys.stderr);sys.exit(2)
